# Generated by Django 4.1.5 on 2023-05-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="imie",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nazwisko",
        ),
        migrations.AddField(
            model_name="user",
            name="wiek",
            field=models.IntegerField(null=True),
        ),
    ]
