# Generated by Django 4.1.5 on 2023-05-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_imie_remove_user_nazwisko_user_wiek"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dolaczenie",
            field=models.DateField(default="1970-01-01"),
        ),
        migrations.AddField(
            model_name="user",
            name="imie",
            field=models.CharField(default="brak danych", max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="nazwisko",
            field=models.CharField(default="brak danych", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="telefon",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="wiek",
            field=models.IntegerField(default=18),
        ),
    ]
