# Generated by Django 4.1.5 on 2023-05-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_dolaczenie_user_imie_user_nazwisko_user_telefon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dolaczenie",
            field=models.DateField(default="1970-01-01"),
        ),
    ]
