# Generated by Django 4.1.5 on 2023-05-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_dolaczenie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="imie",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nazwisko",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="telefon",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="wiek",
            field=models.IntegerField(null=True),
        ),
    ]
